### ISSUE TITLE
Question about electronics

### ISSUE THREAD

**Issue by nekromant** [misteu/RPiCoffee#6]
Hello! Thanks for the awesome project! Can you share some higher quality pics of the display board? Especially the markings on the two ICs (They look like shift registers at first glance). 

I recently got myself this coffee machine and I also plan to make it smart. However I decided on a different approach: I want to just redesign the board with leds and buttons to a custom-made with a esp8266(esphome) onboard so that it would just be a snap-in replacement. 

Thanks!

**Comment by misteu** [comment]
Hey!
Sorry that I saw your comment only now. I might have accidentally turned off notifications :(

As far as I remember, there is a maintenance manual flying around somewhere in the internet which has a lot (if not all) of the schematics.

If you google for "delonghi magnifica schematic" there is a lot of stuff coming up, maybe there is also what you need :)

**Comment by nekromant** [comment]
It also took me a while to notice your response, so we're even ;) 

Meanwhile I found this writeup, so the only thing remaining is just hooking a pcb and writing a esphome component, which is what I will be doing pretty soon.

https://stevep.xyz/2018/05/17/delonghi-magnifica-now-with-alexa/
